---
openapi: 3.0.3
info:
  title: onecx-parameters operator service V1
  description: This API provides endpoints to create and update parameters by the onecx-parameter-operator only
  version: "1.0.0"
servers:
- url: http://onecx-parameters-svc:8080/
tags:
- name: operatorParameters
  description: Create and Update Parameters by the Operator
paths:
  /operator/v1/parameters/{productName}/{applicationId}:
    put:
      security:
        - oauth2: [ ocx-pa-op:write ]
      tags:
      - operatorParameters
      description: Create or update a parameter by product name and application id
      operationId: createOrUpdateParameterValue
      parameters:
        - in: path
          name: productName
          schema:
            type: string
          required: true
        - in: path
          name: applicationId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametersUpdateRequest'
      responses:
        "204":
          description: Parameter created or updated successfully
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        "404":
          description: Not Found
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-pa-op:write: Grants write access
  schemas:
    ParametersUpdateRequest:
      type: object
      properties:
        parameters:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ParameterUpdateRequest'
    ParameterUpdateRequest:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
        displayName:
          type: string
        value:
          type: object
        description:
          type: string
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string